name: helloworld x86-64

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'build tag, eg: "插件名称".'
        required: true
        default: ''

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@go1.20
        env:
          ARCH: ${{ matrix.arch }}-openwrt-21.02
          FEEDNAME: packages_ci
          PACKAGES: luci-app-${{ github.event.inputs.tag }}
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.workflow_token }}
          allowUpdates: true
          replacesArtifacts: true
          tag: "${{ github.event.inputs.tag }}-${{ matrix.arch }}-$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"

      - name: TG
        run: curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=恭喜主人${{ github.event.inputs.tag }}-${{ matrix.arch }}.ipk编译完成！%0A编译时间：$(TZ='Asia/Shanghai' date +@%Y%m%d)%0A下载地址：https://github.com/firkerword/openwrt-Exclusive/releases/tag/${{ github.event.inputs.tag }}-${{ matrix.arch }}-$(TZ='Asia/Shanghai' date +@%Y%m%d)"
  
